#cloud-config

package_update: false
package_upgrade: false

packages:
  - unzip

runcmd:
  - cd /tmp
  - wget scapy.net -O scapy-latest.zip
  - unzip /tmp/scapy-latest.zip -d /opt/
  - cd /opt/scapy-2.*
  - sudo python setup.py install
